name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14'

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "mjack@starrez.com"
    
      - run: npm install

      - run: npx nx affected --target=build

      - run: npx nx affected --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      # - run: npm run semantic
      - run: npm run manifest

      # - name: Tag last-release
      #   shell: bash
      #   run: |
      #     git tag -f last-release
      #     git push origin last-release --force



