name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14'
    
      - run: npm install
      # - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build

      - run: npx nx affected --target=make
      # - run: npx nx affected --target=test --parallel --max-parallel=3
      # - run: npx nx affected --target=lint --parallel --max-parallel=3
      # - run: npx nx affected --target=e2e --parallel --max-parallel=1
      # - run: npx nx-cloud stop-all-agents     
